export const procIdOptions = [
    { code: "AUB", name: "Asia United Bank CA/SA" },
    { code: "BDO", name: "Banco de Oro CA/SA" },
    { code: "BPI", name: "BPI CA/SA" },
    { code: "BFB", name: "BPI Family Bank" },
    { code: "CBC", name: "Chinabank CA/SA" },
    { code: "EWB ", name: "EastWest CA/SA" },
    { code: "LBP", name: "Landbank CA/SA" },
    { code: "MBTC", name: "Metrobank CA/SA" },
    { code: "PNB", name: "PNB individual CA/SA" },
    {
        code: "RCBC ",
        name: "RCBC CA/SA, RCBC Savings Bank CA/SA, RCBC MyWallet",
    },
    { code: "RSB", name: "Robinsons Bank CA/SA" },
    { code: "SBC", name: "Security Bank CA/SA" },
    { code: "UBP", name: "Unionbank CA/SA, EON" },
    { code: "UCPB ", name: "UCPB CA/SA" },
    { code: "MAY ", name: "Maybank" },
    { code: "SBA ", name: "Sterling Bank of Asia" },
    { code: "PBCM ", name: "Philippine Bank of Communications" },
    { code: "PSB ", name: "Philippine Savings Bank" },
    { code: "PVB ", name: "Philippine Savings Bank" },
    { code: "BOC ", name: "Bank of Commerce" },
    { code: "CBCS ", name: "Chinabank Savings Bank" },
    { code: "CTBC ", name: "Chinatrust" },
    { code: "PYMY ", name: "Smart PayMaya" },
];
