export const countryCode = [
    { name: "United States", countryCode: "US" },
    { name: "Canada", countryCode: "CA" },
    { name: "United Kingdom", countryCode: "GB" },
    { name: "Australia", countryCode: "AU" },
    { name: "Germany", countryCode: "DE" },
    { name: "France", countryCode: "FR" },
    { name: "Japan", countryCode: "JP" },
    { name: "China", countryCode: "CN" },
    { name: "India", countryCode: "IN" },
    { name: "Brazil", countryCode: "BR" },
    { name: "Russia", countryCode: "RU" },
    { name: "Mexico", countryCode: "MX" },
    { name: "Italy", countryCode: "IT" },
    { name: "South Korea", countryCode: "KR" },
    { name: "South Africa", countryCode: "ZA" },
    { name: "Nigeria", countryCode: "NG" },
    { name: "Egypt", countryCode: "EG" },
    { name: "Turkey", countryCode: "TR" },
    { name: "Argentina", countryCode: "AR" },
    { name: "Indonesia", countryCode: "ID" },
    { name: "Saudi Arabia", countryCode: "SA" },
    { name: "Spain", countryCode: "ES" },
    { name: "Ukraine", countryCode: "UA" },
    { name: "Colombia", countryCode: "CO" },
    { name: "Thailand", countryCode: "TH" },
    { name: "Kenya", countryCode: "KE" },
    { name: "Pakistan", countryCode: "PK" },
    { name: "Bangladesh", countryCode: "BD" },
    { name: "Vietnam", countryCode: "VN" },
    { name: "Philippines", countryCode: "PH" },
    { name: "Malaysia", countryCode: "MY" },
    { name: "Chile", countryCode: "CL" },
    { name: "Netherlands", countryCode: "NL" },
    { name: "Belgium", countryCode: "BE" },
    { name: "Sweden", countryCode: "SE" },
    { name: "Switzerland", countryCode: "CH" },
    { name: "Norway", countryCode: "NO" },
    { name: "Finland", countryCode: "FI" },
    { name: "Denmark", countryCode: "DK" },
    { name: "Greece", countryCode: "GR" },
    { name: "Portugal", countryCode: "PT" },
    { name: "Israel", countryCode: "IL" },
    { name: "New Zealand", countryCode: "NZ" },
    { name: "Ireland", countryCode: "IE" },
    { name: "Czech Republic", countryCode: "CZ" },
    { name: "Hungary", countryCode: "HU" },
    { name: "Romania", countryCode: "RO" },
    { name: "Poland", countryCode: "PL" },
    { name: "Austria", countryCode: "AT" },
    { name: "South Sudan", countryCode: "SS" },
    { name: "Afghanistan", countryCode: "AF" },
    { name: "Albania", countryCode: "AL" },
    { name: "Algeria", countryCode: "DZ" },
    { name: "Andorra", countryCode: "AD" },
    { name: "Angola", countryCode: "AO" },
    { name: "Antigua and Barbuda", countryCode: "AG" },
    { name: "Armenia", countryCode: "AM" },
    { name: "Azerbaijan", countryCode: "AZ" },
    { name: "Bahamas", countryCode: "BS" },
    { name: "Bahrain", countryCode: "BH" },
    { name: "Barbados", countryCode: "BB" },
    { name: "Belarus", countryCode: "BY" },
    { name: "Belize", countryCode: "BZ" },
    { name: "Benin", countryCode: "BJ" },
    { name: "Bhutan", countryCode: "BT" },
    { name: "Bolivia", countryCode: "BO" },
    { name: "Bosnia and Herzegovina", countryCode: "BA" },
    { name: "Botswana", countryCode: "BW" },
    { name: "Brunei", countryCode: "BN" },
    { name: "Bulgaria", countryCode: "BG" },
    { name: "Burkina Faso", countryCode: "BF" },
    { name: "Burundi", countryCode: "BI" },
    { name: "Cabo Verde", countryCode: "CV" },
    { name: "Cambodia", countryCode: "KH" },
    { name: "Cameroon", countryCode: "CM" },
    { name: "Central African Republic", countryCode: "CF" },
    { name: "Chad", countryCode: "TD" },
    { name: "Comoros", countryCode: "KM" },
    { name: "Congo, Democratic Republic of the", countryCode: "CD" },
    { name: "Congo, Republic of the", countryCode: "CG" },
    { name: "Costa Rica", countryCode: "CR" },
    { name: "Croatia", countryCode: "HR" },
    { name: "Cuba", countryCode: "CU" },
    { name: "Cyprus", countryCode: "CY" },
    { name: "Djibouti", countryCode: "DJ" },
    { name: "Dominica", countryCode: "DM" },
    { name: "Dominican Republic", countryCode: "DO" },
    { name: "East Timor (Timor-Leste)", countryCode: "TL" },
    { name: "Ecuador", countryCode: "EC" },
    { name: "El Salvador", countryCode: "SV" },
    { name: "Equatorial Guinea", countryCode: "GQ" },
    { name: "Eritrea", countryCode: "ER" },
    { name: "Estonia", countryCode: "EE" },
    { name: "Eswatini", countryCode: "SZ" },
    { name: "Fiji", countryCode: "FJ" },
    { name: "Gabon", countryCode: "GA" },
    { name: "Gambia", countryCode: "GM" },
    { name: "Georgia", countryCode: "GE" },
    { name: "Ghana", countryCode: "GH" },
    { name: "Grenada", countryCode: "GD" },
    { name: "Guatemala", countryCode: "GT" },
    { name: "Guinea", countryCode: "GN" },
    { name: "Guinea-Bissau", countryCode: "GW" },
    { name: "Guyana", countryCode: "GY" },
    { name: "Haiti", countryCode: "HT" },
    { name: "Honduras", countryCode: "HN" },
    { name: "Iceland", countryCode: "IS" },
    { name: "Iraq", countryCode: "IQ" },
    { name: "Jamaica", countryCode: "JM" },
    { name: "Jordan", countryCode: "JO" },
    { name: "Kazakhstan", countryCode: "KZ" },
    { name: "Kuwait", countryCode: "KW" },
    { name: "Kyrgyzstan", countryCode: "KG" },
    { name: "Laos", countryCode: "LA" },
    { name: "Latvia", countryCode: "LV" },
    { name: "Lebanon", countryCode: "LB" },
    { name: "Lesotho", countryCode: "LS" },
    { name: "Liberia", countryCode: "LR" },
    { name: "Libya", countryCode: "LY" },
    { name: "Liechtenstein", countryCode: "LI" },
    { name: "Lithuania", countryCode: "LT" },
    { name: "Luxembourg", countryCode: "LU" },
    { name: "Madagascar", countryCode: "MG" },
    { name: "Malawi", countryCode: "MW" },
    { name: "Maldives", countryCode: "MV" },
    { name: "Mali", countryCode: "ML" },
    { name: "Malta", countryCode: "MT" },
    { name: "Mauritania", countryCode: "MR" },
    { name: "Mauritius", countryCode: "MU" },
    { name: "Micronesia", countryCode: "FM" },
    { name: "Moldova", countryCode: "MD" },
    { name: "Monaco", countryCode: "MC" },
    { name: "Mongolia", countryCode: "MN" },
    { name: "Montenegro", countryCode: "ME" },
    { name: "Morocco", countryCode: "MA" },
    { name: "Mozambique", countryCode: "MZ" },
    { name: "Myanmar (Burma)", countryCode: "MM" },
    { name: "Namibia", countryCode: "NA" },
    { name: "Nauru", countryCode: "NR" },
    { name: "Nepal", countryCode: "NP" },
    { name: "Nicaragua", countryCode: "NI" },
    { name: "Niger", countryCode: "NE" },
    { name: "North Macedonia", countryCode: "MK" },
    { name: "Oman", countryCode: "OM" },
    { name: "Palau", countryCode: "PW" },
    { name: "Panama", countryCode: "PA" },
    { name: "Papua New Guinea", countryCode: "PG" },
    { name: "Paraguay", countryCode: "PY" },
    { name: "Peru", countryCode: "PE" },
    { name: "Qatar", countryCode: "QA" },
    { name: "Rwanda", countryCode: "RW" },
    { name: "Saint Kitts and Nevis", countryCode: "KN" },
    { name: "Saint Lucia", countryCode: "LC" },
    { name: "Saint Vincent and the Grenadines", countryCode: "VC" },
    { name: "Samoa", countryCode: "WS" },
    { name: "San Marino", countryCode: "SM" },
    { name: "Sao Tome and Principe", countryCode: "ST" },
    { name: "Senegal", countryCode: "SN" },
    { name: "Serbia", countryCode: "RS" },
    { name: "Seychelles", countryCode: "SC" },
    { name: "Sierra Leone", countryCode: "SL" },
    { name: "Singapore", countryCode: "SG" },
    { name: "Slovakia", countryCode: "SK" },
    { name: "Slovenia", countryCode: "SI" },
    { name: "Solomon Islands", countryCode: "SB" },
    { name: "Somalia", countryCode: "SO" },
    { name: "Sri Lanka", countryCode: "LK" },
    { name: "Sudan", countryCode: "SD" },
    { name: "Suriname", countryCode: "SR" },
    { name: "Syria", countryCode: "SY" },
    { name: "Tajikistan", countryCode: "TJ" },
    { name: "Tanzania", countryCode: "TZ" },
    { name: "Togo", countryCode: "TG" },
    { name: "Tonga", countryCode: "TO" },
    { name: "Trinidad and Tobago", countryCode: "TT" },
    { name: "Tunisia", countryCode: "TN" },
    { name: "Turkmenistan", countryCode: "TM" },
    { name: "Tuvalu", countryCode: "TV" },
    { name: "Uganda", countryCode: "UG" },
    { name: "United Arab Emirates", countryCode: "AE" },
    { name: "Uruguay", countryCode: "UY" },
    { name: "Uzbekistan", countryCode: "UZ" },
    { name: "Vanuatu", countryCode: "VU" },
    { name: "Vatican City", countryCode: "VA" },
    { name: "Venezuela", countryCode: "VE" },
    { name: "Yemen", countryCode: "YE" },
    { name: "Zambia", countryCode: "ZM" },
    { name: "Zimbabwe", countryCode: "ZW" },
];
