export const products = [
    {
        id: 1,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 1000,
    },
    {
        id: 2,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 2000,
    },
    {
        id: 3,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 3000,
    },
    {
        id: 4,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 4000,
    },
    {
        id: 5,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 5000,
    },
    {
        id: 6,
        title: "Laser Quest Bukit Batok",
        subTitle: "Singapore",
        activity: "Tours, Sightseeing, and Activities",
        experience: "Nolvety and Speciality Tours",
        src: "/src/assets/images/product/singapore-placeholder.png",
        price: 6000,
    },
];
