export const countriesInfo = [
    {
        index: 1,
        name: "Aruba",
        code: "AW",
        callingCode: "297",
        currencyCode: "AWG",
    },
    {
        index: 2,
        name: "Afghanistan",
        code: "AF",
        callingCode: "93",
        currencyCode: "AFN",
    },
    {
        index: 3,
        name: "Angola",
        code: "AO",
        callingCode: "244",
        currencyCode: "AOA",
    },
    {
        index: 4,
        name: "Anguilla",
        code: "AI",
        callingCode: "1264",
        currencyCode: "XCD",
    },
    {
        index: 5,
        name: "Ãland Islands",
        code: "AX",
        callingCode: "358",
        currencyCode: "EUR",
    },
    {
        index: 6,
        name: "Albania",
        code: "AL",
        callingCode: "355",
        currencyCode: "ALL",
    },
    {
        index: 7,
        name: "Andorra",
        code: "AD",
        callingCode: "376",
        currencyCode: "EUR",
    },
    {
        index: 8,
        name: "United Arab Emirates",
        code: "AE",
        callingCode: "971",
        currencyCode: "AED",
    },
    {
        index: 9,
        name: "Argentina",
        code: "AR",
        callingCode: "54",
        currencyCode: "ARS",
    },
    {
        index: 10,
        name: "Armenia",
        code: "AM",
        callingCode: "374",
        currencyCode: "AMD",
    },
    {
        index: 11,
        name: "American Samoa",
        code: "AS",
        callingCode: "1684",
        currencyCode: "USD",
    },
    {
        index: 12,
        name: "Antigua and Barbuda",
        code: "AG",
        callingCode: "1268",
        currencyCode: "XCD",
    },
    {
        index: 13,
        name: "Australia",
        code: "AU",
        callingCode: "61",
        currencyCode: "AUD",
    },
    {
        index: 14,
        name: "Austria",
        code: "AT",
        callingCode: "43",
        currencyCode: "EUR",
    },
    {
        index: 15,
        name: "Azerbaijan",
        code: "AZ",
        callingCode: "994",
        currencyCode: "AZN",
    },
    {
        index: 16,
        name: "Burundi",
        code: "BI",
        callingCode: "257",
        currencyCode: "BIF",
    },
    {
        index: 17,
        name: "Belgium",
        code: "BE",
        callingCode: "32",
        currencyCode: "EUR",
    },
    {
        index: 18,
        name: "Benin",
        code: "BJ",
        callingCode: "229",
        currencyCode: "XOF",
    },
    {
        index: 19,
        name: "Burkina Faso",
        code: "BF",
        callingCode: "226",
        currencyCode: "XOF",
    },
    {
        index: 20,
        name: "Bangladesh",
        code: "BD",
        callingCode: "880",
        currencyCode: "BDT",
    },
    {
        index: 21,
        name: "Bulgaria",
        code: "BG",
        callingCode: "359",
        currencyCode: "BGN",
    },
    {
        index: 22,
        name: "Bahrain",
        code: "BH",
        callingCode: "973",
        currencyCode: "BHD",
    },
    {
        index: 23,
        name: "Bahamas",
        code: "BS",
        callingCode: "1242",
        currencyCode: "BSD",
    },
    {
        index: 24,
        name: "Bosnia and Herzegovina",
        code: "BA",
        callingCode: "387",
        currencyCode: "BAM",
    },
    {
        index: 25,
        name: "Saint BarthÃ©lemy",
        code: "BL",
        callingCode: "590",
        currencyCode: "EUR",
    },
    {
        index: 26,
        name: "Belarus",
        code: "BY",
        callingCode: "375",
        currencyCode: "BYN",
    },
    {
        index: 27,
        name: "Belize",
        code: "BZ",
        callingCode: "501",
        currencyCode: "BZD",
    },
    {
        index: 28,
        name: "Bermuda",
        code: "BM",
        callingCode: "1441",
        currencyCode: "BMD",
    },
    {
        index: 29,
        name: "Bolivia",
        code: "BO",
        callingCode: "591",
        currencyCode: "BOB",
    },
    {
        index: 30,
        name: "Brazil",
        code: "BR",
        callingCode: "55",
        currencyCode: "BRL",
    },
    {
        index: 31,
        name: "Barbados",
        code: "BB",
        callingCode: "1246",
        currencyCode: "BBD",
    },
    {
        index: 32,
        name: "Brunei",
        code: "BN",
        callingCode: "673",
        currencyCode: "BND",
    },
    {
        index: 33,
        name: "Bhutan",
        code: "BT",
        callingCode: "975",
        currencyCode: "BTN",
    },
    {
        index: 34,
        name: "Botswana",
        code: "BW",
        callingCode: "267",
        currencyCode: "BWP",
    },
    {
        index: 35,
        name: "Central African Republic",
        code: "CF",
        callingCode: "236",
        currencyCode: "XAF",
    },
    {
        index: 36,
        name: "Canada",
        code: "CA",
        callingCode: "1",
        currencyCode: "CAD",
    },
    {
        index: 37,
        name: "Cocos (Keeling) Islands",
        code: "CC",
        callingCode: "61",
        currencyCode: "AUD",
    },
    {
        index: 38,
        name: "Switzerland",
        code: "CH",
        callingCode: "41",
        currencyCode: "CHF",
    },
    {
        index: 39,
        name: "Chile",
        code: "CL",
        callingCode: "56",
        currencyCode: "CLP",
    },
    {
        index: 40,
        name: "China",
        code: "CN",
        callingCode: "86",
        currencyCode: "CNY",
    },
    {
        index: 41,
        name: "Ivory Coast",
        code: "CI",
        callingCode: "225",
        currencyCode: "XOF",
    },
    {
        index: 42,
        name: "Cameroon",
        code: "CM",
        callingCode: "237",
        currencyCode: "XAF",
    },
    {
        index: 43,
        name: "DR Congo",
        code: "CD",
        callingCode: "243",
        currencyCode: "CDF",
    },
    {
        index: 44,
        name: "Republic of the Congo",
        code: "CG",
        callingCode: "242",
        currencyCode: "XAF",
    },
    {
        index: 45,
        name: "Cook Islands",
        code: "CK",
        callingCode: "682",
        currencyCode: "NZD",
    },
    {
        index: 46,
        name: "Colombia",
        code: "CO",
        callingCode: "57",
        currencyCode: "COP",
    },
    {
        index: 47,
        name: "Comoros",
        code: "KM",
        callingCode: "269",
        currencyCode: "KMF",
    },
    {
        index: 48,
        name: "Cape Verde",
        code: "CV",
        callingCode: "238",
        currencyCode: "CVE",
    },
    {
        index: 49,
        name: "Costa Rica",
        code: "CR",
        callingCode: "506",
        currencyCode: "CRC",
    },
    {
        index: 50,
        name: "Cuba",
        code: "CU",
        callingCode: "53",
        currencyCode: "CUP",
    },
    {
        index: 51,
        name: "CuraÃ§ao",
        code: "CW",
        callingCode: "5999",
        currencyCode: "ANG",
    },
    {
        index: 52,
        name: "Christmas Island",
        code: "CX",
        callingCode: "61",
        currencyCode: "AUD",
    },
    {
        index: 53,
        name: "Cayman Islands",
        code: "KY",
        callingCode: "1345",
        currencyCode: "KYD",
    },
    {
        index: 54,
        name: "Cyprus",
        code: "CY",
        callingCode: "357",
        currencyCode: "EUR",
    },
    {
        index: 55,
        name: "Czechia",
        code: "CZ",
        callingCode: "420",
        currencyCode: "CZK",
    },
    {
        index: 56,
        name: "Germany",
        code: "DE",
        callingCode: "49",
        currencyCode: "EUR",
    },
    {
        index: 57,
        name: "Djibouti",
        code: "DJ",
        callingCode: "253",
        currencyCode: "DJF",
    },
    {
        index: 58,
        name: "Dominica",
        code: "DM",
        callingCode: "1767",
        currencyCode: "XCD",
    },
    {
        index: 59,
        name: "Denmark",
        code: "DK",
        callingCode: "45",
        currencyCode: "DKK",
    },
    {
        index: 60,
        name: "Dominican Republic 1809",
        code: "DO",
        callingCode: "1809",
        currencyCode: "DOP",
    },
    {
        index: 61,
        name: "Dominican Republic 1829",
        code: "DO",
        callingCode: "1829",
        currencyCode: "DOP",
    },
    {
        index: 62,
        name: "Dominican Republic 1849",
        code: "DO",
        callingCode: "1849",
        currencyCode: "DOP",
    },
    {
        index: 63,
        name: "Algeria",
        code: "DZ",
        callingCode: "213",
        currencyCode: "DZD",
    },
    {
        index: 64,
        name: "Ecuador",
        code: "EC",
        callingCode: "593",
        currencyCode: "USD",
    },
    {
        index: 65,
        name: "Egypt",
        code: "EG",
        callingCode: "20",
        currencyCode: "EGP",
    },
    {
        index: 66,
        name: "Eritrea",
        code: "ER",
        callingCode: "291",
        currencyCode: "ERN",
    },
    {
        index: 67,
        name: "Western Sahara",
        code: "EH",
        callingCode: "212",
        currencyCode: "MAD",
    },
    {
        index: 68,
        name: "Spain",
        code: "ES",
        callingCode: "34",
        currencyCode: "EUR",
    },
    {
        index: 69,
        name: "Estonia",
        code: "EE",
        callingCode: "372",
        currencyCode: "EUR",
    },
    {
        index: 70,
        name: "Ethiopia",
        code: "ET",
        callingCode: "251",
        currencyCode: "ETB",
    },
    {
        index: 71,
        name: "Finland",
        code: "FI",
        callingCode: "358",
        currencyCode: "EUR",
    },
    {
        index: 72,
        name: "Fiji",
        code: "FJ",
        callingCode: "679",
        currencyCode: "FJD",
    },
    {
        index: 73,
        name: "Falkland Islands",
        code: "FK",
        callingCode: "500",
        currencyCode: "FKP",
    },
    {
        index: 74,
        name: "France",
        code: "FR",
        callingCode: "33",
        currencyCode: "EUR",
    },
    {
        index: 75,
        name: "Faroe Islands",
        code: "FO",
        callingCode: "298",
        currencyCode: "DKK",
    },
    {
        index: 76,
        name: "Micronesia",
        code: "FM",
        callingCode: "691",
        currencyCode: "USD",
    },
    {
        index: 77,
        name: "Gabon",
        code: "GA",
        callingCode: "241",
        currencyCode: "XAF",
    },
    {
        index: 78,
        name: "United Kingdom",
        code: "GB",
        callingCode: "44",
        currencyCode: "GBP",
    },
    {
        index: 79,
        name: "Georgia",
        code: "GE",
        callingCode: "995",
        currencyCode: "GEL",
    },
    {
        index: 80,
        name: "Guernsey",
        code: "GG",
        callingCode: "44",
        currencyCode: "GBP",
    },
    {
        index: 81,
        name: "Ghana",
        code: "GH",
        callingCode: "233",
        currencyCode: "GHS",
    },
    {
        index: 82,
        name: "Gibraltar",
        code: "GI",
        callingCode: "350",
        currencyCode: "GIP",
    },
    {
        index: 83,
        name: "Guinea",
        code: "GN",
        callingCode: "224",
        currencyCode: "GNF",
    },
    {
        index: 84,
        name: "Guadeloupe",
        code: "GP",
        callingCode: "590",
        currencyCode: "EUR",
    },
    {
        index: 85,
        name: "Gambia",
        code: "GM",
        callingCode: "220",
        currencyCode: "GMD",
    },
    {
        index: 86,
        name: "Guinea-Bissau",
        code: "GW",
        callingCode: "245",
        currencyCode: "XOF",
    },
    {
        index: 87,
        name: "Equatorial Guinea",
        code: "GQ",
        callingCode: "240",
        currencyCode: "XAF",
    },
    {
        index: 88,
        name: "Greece",
        code: "GR",
        callingCode: "30",
        currencyCode: "EUR",
    },
    {
        index: 89,
        name: "Grenada",
        code: "GD",
        callingCode: "1473",
        currencyCode: "XCD",
    },
    {
        index: 90,
        name: "Greenland",
        code: "GL",
        callingCode: "299",
        currencyCode: "DKK",
    },
    {
        index: 91,
        name: "Guatemala",
        code: "GT",
        callingCode: "502",
        currencyCode: "GTQ",
    },
    {
        index: 92,
        name: "French Guiana",
        code: "GF",
        callingCode: "594",
        currencyCode: "EUR",
    },
    {
        index: 93,
        name: "Guam",
        code: "GU",
        callingCode: "1671",
        currencyCode: "USD",
    },
    {
        index: 94,
        name: "Guyana",
        code: "GY",
        callingCode: "592",
        currencyCode: "GYD",
    },
    {
        index: 95,
        name: "Hong Kong",
        code: "HK",
        callingCode: "852",
        currencyCode: "HKD",
    },
    {
        index: 96,
        name: "Honduras",
        code: "HN",
        callingCode: "504",
        currencyCode: "HNL",
    },
    {
        index: 97,
        name: "Croatia",
        code: "HR",
        callingCode: "385",
        currencyCode: "HRK",
    },
    {
        index: 98,
        name: "Haiti",
        code: "HT",
        callingCode: "509",
        currencyCode: "HTG",
    },
    {
        index: 99,
        name: "Hungary",
        code: "HU",
        callingCode: "36",
        currencyCode: "HUF",
    },
    {
        index: 100,
        name: "Indonesia",
        code: "ID",
        callingCode: "62",
        currencyCode: "IDR",
    },
    {
        index: 101,
        name: "Isle of Man",
        code: "IM",
        callingCode: "44",
        currencyCode: "GBP",
    },
    {
        index: 102,
        name: "India",
        code: "IN",
        callingCode: "91",
        currencyCode: "INR",
    },
    {
        index: 103,
        name: "British Indian Ocean Territory",
        code: "IO",
        callingCode: "246",
        currencyCode: "USD",
    },
    {
        index: 104,
        name: "Ireland",
        code: "IE",
        callingCode: "353",
        currencyCode: "EUR",
    },
    {
        index: 105,
        name: "Iran",
        code: "IR",
        callingCode: "98",
        currencyCode: "IRR",
    },
    {
        index: 106,
        name: "Iraq",
        code: "IQ",
        callingCode: "964",
        currencyCode: "IQD",
    },
    {
        index: 107,
        name: "Iceland",
        code: "IS",
        callingCode: "354",
        currencyCode: "ISK",
    },
    {
        index: 108,
        name: "Israel",
        code: "IL",
        callingCode: "972",
        currencyCode: "ILS",
    },
    {
        index: 109,
        name: "Italy",
        code: "IT",
        callingCode: "39",
        currencyCode: "EUR",
    },
    {
        index: 110,
        name: "Jamaica",
        code: "JM",
        callingCode: "1876",
        currencyCode: "JMD",
    },
    {
        index: 111,
        name: "Jersey",
        code: "JE",
        callingCode: "44",
        currencyCode: "GBP",
    },
    {
        index: 112,
        name: "Jordan",
        code: "JO",
        callingCode: "962",
        currencyCode: "JOD",
    },
    {
        index: 113,
        name: "Japan",
        code: "JP",
        callingCode: "81",
        currencyCode: "JPY",
    },
    {
        index: 114,
        name: "Kazakhstan 76",
        code: "KZ",
        callingCode: "76",
        currencyCode: "KZT",
    },
    {
        index: 115,
        name: "Kazakhstan 77",
        code: "KZ",
        callingCode: "77",
        currencyCode: "KZT",
    },
    {
        index: 116,
        name: "Kenya",
        code: "KE",
        callingCode: "254",
        currencyCode: "KES",
    },
    {
        index: 117,
        name: "Kyrgyzstan",
        code: "KG",
        callingCode: "996",
        currencyCode: "KGS",
    },
    {
        index: 118,
        name: "Cambodia",
        code: "KH",
        callingCode: "855",
        currencyCode: "KHR",
    },
    {
        index: 119,
        name: "Kiribati",
        code: "KI",
        callingCode: "686",
        currencyCode: "AUD",
    },
    {
        index: 120,
        name: "Saint Kitts and Nevis",
        code: "KN",
        callingCode: "1869",
        currencyCode: "XCD",
    },
    {
        index: 121,
        name: "South Korea",
        code: "KR",
        callingCode: "82",
        currencyCode: "KRW",
    },
    {
        index: 122,
        name: "Kosovo",
        code: "XK",
        callingCode: "383",
        currencyCode: "EUR",
    },
    {
        index: 123,
        name: "Kuwait",
        code: "KW",
        callingCode: "965",
        currencyCode: "KWD",
    },
    {
        index: 124,
        name: "Laos",
        code: "LA",
        callingCode: "856",
        currencyCode: "LAK",
    },
    {
        index: 125,
        name: "Lebanon",
        code: "LB",
        callingCode: "961",
        currencyCode: "LBP",
    },
    {
        index: 126,
        name: "Liberia",
        code: "LR",
        callingCode: "231",
        currencyCode: "LRD",
    },
    {
        index: 127,
        name: "Libya",
        code: "LY",
        callingCode: "218",
        currencyCode: "LYD",
    },
    {
        index: 128,
        name: "Saint Lucia",
        code: "LC",
        callingCode: "1758",
        currencyCode: "XCD",
    },
    {
        index: 129,
        name: "Liechtenstein",
        code: "LI",
        callingCode: "423",
        currencyCode: "CHF",
    },
    {
        index: 130,
        name: "Sri Lanka",
        code: "LK",
        callingCode: "94",
        currencyCode: "LKR",
    },
    {
        index: 131,
        name: "Lesotho",
        code: "LS",
        callingCode: "266",
        currencyCode: "LSL",
    },
    {
        index: 132,
        name: "Lithuania",
        code: "LT",
        callingCode: "370",
        currencyCode: "EUR",
    },
    {
        index: 133,
        name: "Luxembourg",
        code: "LU",
        callingCode: "352",
        currencyCode: "EUR",
    },
    {
        index: 134,
        name: "Latvia",
        code: "LV",
        callingCode: "371",
        currencyCode: "EUR",
    },
    {
        index: 135,
        name: "Macau",
        code: "MO",
        callingCode: "853",
        currencyCode: "MOP",
    },
    {
        index: 136,
        name: "Saint Martin",
        code: "MF",
        callingCode: "590",
        currencyCode: "EUR",
    },
    {
        index: 137,
        name: "Morocco",
        code: "MA",
        callingCode: "212",
        currencyCode: "MAD",
    },
    {
        index: 138,
        name: "Monaco",
        code: "MC",
        callingCode: "377",
        currencyCode: "EUR",
    },
    {
        index: 139,
        name: "Moldova",
        code: "MD",
        callingCode: "373",
        currencyCode: "MDL",
    },
    {
        index: 140,
        name: "Madagascar",
        code: "MG",
        callingCode: "261",
        currencyCode: "MGA",
    },
    {
        index: 141,
        name: "Maldives",
        code: "MV",
        callingCode: "960",
        currencyCode: "MVR",
    },
    {
        index: 142,
        name: "Mexico",
        code: "MX",
        callingCode: "52",
        currencyCode: "MXN",
    },
    {
        index: 143,
        name: "Marshall Islands",
        code: "MH",
        callingCode: "692",
        currencyCode: "USD",
    },
    {
        index: 144,
        name: "Macedonia",
        code: "MK",
        callingCode: "389",
        currencyCode: "MKD",
    },
    {
        index: 145,
        name: "Mali",
        code: "ML",
        callingCode: "223",
        currencyCode: "XOF",
    },
    {
        index: 146,
        name: "Malta",
        code: "MT",
        callingCode: "356",
        currencyCode: "EUR",
    },
    {
        index: 147,
        name: "Myanmar",
        code: "MM",
        callingCode: "95",
        currencyCode: "MMK",
    },
    {
        index: 148,
        name: "Montenegro",
        code: "ME",
        callingCode: "382",
        currencyCode: "EUR",
    },
    {
        index: 149,
        name: "Mongolia",
        code: "MN",
        callingCode: "976",
        currencyCode: "MNT",
    },
    {
        index: 150,
        name: "Northern Mariana Islands",
        code: "MP",
        callingCode: "1670",
        currencyCode: "USD",
    },
    {
        index: 151,
        name: "Mozambique",
        code: "MZ",
        callingCode: "258",
        currencyCode: "MZN",
    },
    {
        index: 152,
        name: "Mauritania",
        code: "MR",
        callingCode: "222",
        currencyCode: "MRU",
    },
    {
        index: 153,
        name: "Montserrat",
        code: "MS",
        callingCode: "1664",
        currencyCode: "XCD",
    },
    {
        index: 154,
        name: "Martinique",
        code: "MQ",
        callingCode: "596",
        currencyCode: "EUR",
    },
    {
        index: 155,
        name: "Mauritius",
        code: "MU",
        callingCode: "230",
        currencyCode: "MUR",
    },
    {
        index: 156,
        name: "Malawi",
        code: "MW",
        callingCode: "265",
        currencyCode: "MWK",
    },
    {
        index: 157,
        name: "Malaysia",
        code: "MY",
        callingCode: "60",
        currencyCode: "MYR",
    },
    {
        index: 158,
        name: "Mayotte",
        code: "YT",
        callingCode: "262",
        currencyCode: "EUR",
    },
    {
        index: 159,
        name: "Namibia",
        code: "NA",
        callingCode: "264",
        currencyCode: "NAD",
    },
    {
        index: 160,
        name: "New Caledonia",
        code: "NC",
        callingCode: "687",
        currencyCode: "XPF",
    },
    {
        index: 161,
        name: "Niger",
        code: "NE",
        callingCode: "227",
        currencyCode: "XOF",
    },
    {
        index: 162,
        name: "Norfolk Island",
        code: "NF",
        callingCode: "672",
        currencyCode: "AUD",
    },
    {
        index: 163,
        name: "Nigeria",
        code: "NG",
        callingCode: "234",
        currencyCode: "NGN",
    },
    {
        index: 164,
        name: "Nicaragua",
        code: "NI",
        callingCode: "505",
        currencyCode: "NIO",
    },
    {
        index: 165,
        name: "Niue",
        code: "NU",
        callingCode: "683",
        currencyCode: "NZD",
    },
    {
        index: 166,
        name: "Netherlands",
        code: "NL",
        callingCode: "31",
        currencyCode: "EUR",
    },
    {
        index: 167,
        name: "Norway",
        code: "NO",
        callingCode: "47",
        currencyCode: "NOK",
    },
    {
        index: 168,
        name: "Nepal",
        code: "NP",
        callingCode: "977",
        currencyCode: "NPR",
    },
    {
        index: 169,
        name: "Nauru",
        code: "NR",
        callingCode: "674",
        currencyCode: "AUD",
    },
    {
        index: 170,
        name: "New Zealand",
        code: "NZ",
        callingCode: "64",
        currencyCode: "NZD",
    },
    {
        index: 171,
        name: "Oman",
        code: "OM",
        callingCode: "968",
        currencyCode: "OMR",
    },
    {
        index: 172,
        name: "Pakistan",
        code: "PK",
        callingCode: "92",
        currencyCode: "PKR",
    },
    {
        index: 173,
        name: "Panama",
        code: "PA",
        callingCode: "507",
        currencyCode: "PAB",
    },
    {
        index: 174,
        name: "Pitcairn Islands",
        code: "PN",
        callingCode: "64",
        currencyCode: "NZD",
    },
    {
        index: 175,
        name: "Peru",
        code: "PE",
        callingCode: "51",
        currencyCode: "PEN",
    },
    {
        index: 176,
        name: "Philippines",
        code: "PH",
        callingCode: "63",
        currencyCode: "PHP",
    },
    {
        index: 177,
        name: "Palau",
        code: "PW",
        callingCode: "680",
        currencyCode: "USD",
    },
    {
        index: 178,
        name: "Papua New Guinea",
        code: "PG",
        callingCode: "675",
        currencyCode: "PGK",
    },
    {
        index: 179,
        name: "Poland",
        code: "PL",
        callingCode: "48",
        currencyCode: "PLN",
    },
    {
        index: 180,
        name: "Puerto Rico 1787",
        code: "PR",
        callingCode: "1787",
        currencyCode: "USD",
    },
    {
        index: 181,
        name: "Puerto Rico 1939",
        code: "PR",
        callingCode: "1939",
        currencyCode: "USD",
    },
    {
        index: 182,
        name: "North Korea",
        code: "KP",
        callingCode: "850",
        currencyCode: "KPW",
    },
    {
        index: 183,
        name: "Portugal",
        code: "PT",
        callingCode: "351",
        currencyCode: "EUR",
    },
    {
        index: 184,
        name: "Paraguay",
        code: "PY",
        callingCode: "595",
        currencyCode: "PYG",
    },
    {
        index: 185,
        name: "Palestine",
        code: "PS",
        callingCode: "970",
        currencyCode: "ILS",
    },
    {
        index: 186,
        name: "French Polynesia",
        code: "PF",
        callingCode: "689",
        currencyCode: "XPF",
    },
    {
        index: 187,
        name: "Qatar",
        code: "QA",
        callingCode: "974",
        currencyCode: "QAR",
    },
    {
        index: 188,
        name: "RÃ©union",
        code: "RE",
        callingCode: "262",
        currencyCode: "EUR",
    },
    {
        index: 189,
        name: "Romania",
        code: "RO",
        callingCode: "40",
        currencyCode: "RON",
    },
    {
        index: 190,
        name: "Russia",
        code: "RU",
        callingCode: "7",
        currencyCode: "RUB",
    },
    {
        index: 191,
        name: "Rwanda",
        code: "RW",
        callingCode: "250",
        currencyCode: "RWF",
    },
    {
        index: 192,
        name: "Saudi Arabia",
        code: "SA",
        callingCode: "966",
        currencyCode: "SAR",
    },
    {
        index: 193,
        name: "Sudan",
        code: "SD",
        callingCode: "249",
        currencyCode: "SDG",
    },
    {
        index: 194,
        name: "Senegal",
        code: "SN",
        callingCode: "221",
        currencyCode: "XOF",
    },
    {
        index: 195,
        name: "Singapore",
        code: "SG",
        callingCode: "65",
        currencyCode: "SGD",
    },
    {
        index: 196,
        name: "South Georgia",
        code: "GS",
        callingCode: "500",
        currencyCode: "GBP",
    },
    {
        index: 197,
        name: "Svalbard and Jan Mayen",
        code: "SJ",
        callingCode: "4779",
        currencyCode: "NOK",
    },
    {
        index: 198,
        name: "Solomon Islands",
        code: "SB",
        callingCode: "677",
        currencyCode: "SBD",
    },
    {
        index: 199,
        name: "Sierra Leone",
        code: "SL",
        callingCode: "232",
        currencyCode: "SLL",
    },
    {
        index: 200,
        name: "El Salvador",
        code: "SV",
        callingCode: "503",
        currencyCode: "USD",
    },
    {
        index: 201,
        name: "San Marino",
        code: "SM",
        callingCode: "378",
        currencyCode: "EUR",
    },
    {
        index: 202,
        name: "Somalia",
        code: "SO",
        callingCode: "252",
        currencyCode: "SOS",
    },
    {
        index: 203,
        name: "Saint Pierre and Miquelon",
        code: "PM",
        callingCode: "508",
        currencyCode: "EUR",
    },
    {
        index: 204,
        name: "Serbia",
        code: "RS",
        callingCode: "381",
        currencyCode: "RSD",
    },
    {
        index: 205,
        name: "South Sudan",
        code: "SS",
        callingCode: "211",
        currencyCode: "SSP",
    },
    {
        index: 206,
        name: "SÃ£o TomÃ© and PrÃ­ncipe",
        code: "ST",
        callingCode: "239",
        currencyCode: "STN",
    },
    {
        index: 207,
        name: "Suriname",
        code: "SR",
        callingCode: "597",
        currencyCode: "SRD",
    },
    {
        index: 208,
        name: "Slovakia",
        code: "SK",
        callingCode: "421",
        currencyCode: "EUR",
    },
    {
        index: 209,
        name: "Slovenia",
        code: "SI",
        callingCode: "386",
        currencyCode: "EUR",
    },
    {
        index: 210,
        name: "Sweden",
        code: "SE",
        callingCode: "46",
        currencyCode: "SEK",
    },
    {
        index: 211,
        name: "Swaziland",
        code: "SZ",
        callingCode: "268",
        currencyCode: "SZL",
    },
    {
        index: 212,
        name: "Sint Maarten",
        code: "SX",
        callingCode: "1721",
        currencyCode: "ANG",
    },
    {
        index: 213,
        name: "Seychelles",
        code: "SC",
        callingCode: "248",
        currencyCode: "SCR",
    },
    {
        index: 214,
        name: "Syria",
        code: "SY",
        callingCode: "963",
        currencyCode: "SYP",
    },
    {
        index: 215,
        name: "Turks and Caicos Islands",
        code: "TC",
        callingCode: "1649",
        currencyCode: "USD",
    },
    {
        index: 216,
        name: "Chad",
        code: "TD",
        callingCode: "235",
        currencyCode: "XAF",
    },
    {
        index: 217,
        name: "Togo",
        code: "TG",
        callingCode: "228",
        currencyCode: "XOF",
    },
    {
        index: 218,
        name: "Thailand",
        code: "TH",
        callingCode: "66",
        currencyCode: "THB",
    },
    {
        index: 219,
        name: "Tajikistan",
        code: "TJ",
        callingCode: "992",
        currencyCode: "TJS",
    },
    {
        index: 220,
        name: "Tokelau",
        code: "TK",
        callingCode: "690",
        currencyCode: "NZD",
    },
    {
        index: 221,
        name: "Turkmenistan",
        code: "TM",
        callingCode: "993",
        currencyCode: "TMT",
    },
    {
        index: 222,
        name: "Timor-Leste",
        code: "TL",
        callingCode: "670",
        currencyCode: "USD",
    },
    {
        index: 223,
        name: "Tonga",
        code: "TO",
        callingCode: "676",
        currencyCode: "TOP",
    },
    {
        index: 224,
        name: "Trinidad and Tobago",
        code: "TT",
        callingCode: "1868",
        currencyCode: "TTD",
    },
    {
        index: 225,
        name: "Tunisia",
        code: "TN",
        callingCode: "216",
        currencyCode: "TND",
    },
    {
        index: 226,
        name: "Turkey",
        code: "TR",
        callingCode: "90",
        currencyCode: "TRY",
    },
    {
        index: 227,
        name: "Tuvalu",
        code: "TV",
        callingCode: "688",
        currencyCode: "AUD",
    },
    {
        index: 228,
        name: "Taiwan",
        code: "TW",
        callingCode: "886",
        currencyCode: "TWD",
    },
    {
        index: 229,
        name: "Tanzania",
        code: "TZ",
        callingCode: "255",
        currencyCode: "TZS",
    },
    {
        index: 230,
        name: "Uganda",
        code: "UG",
        callingCode: "256",
        currencyCode: "UGX",
    },
    {
        index: 231,
        name: "Ukraine",
        code: "UA",
        callingCode: "380",
        currencyCode: "UAH",
    },
    {
        index: 232,
        name: "Uruguay",
        code: "UY",
        callingCode: "598",
        currencyCode: "UYU",
    },
    {
        index: 233,
        name: "United States",
        code: "US",
        callingCode: "1",
        currencyCode: "USD",
    },
    {
        index: 234,
        name: "Uzbekistan",
        code: "UZ",
        callingCode: "998",
        currencyCode: "UZS",
    },
    {
        index: 235,
        name: "Vatican City 39",
        code: "VA",
        callingCode: "39",
        currencyCode: "EUR",
    },
    {
        index: 236,
        name: "Vatican City 379",
        code: "VA",
        callingCode: "379",
        currencyCode: "EUR",
    },
    {
        index: 237,
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        callingCode: "1784",
        currencyCode: "XCD",
    },
    {
        index: 238,
        name: "Venezuela",
        code: "VE",
        callingCode: "58",
        currencyCode: "VES",
    },
    {
        index: 239,
        name: "British Virgin Islands",
        code: "VG",
        callingCode: "1284",
        currencyCode: "USD",
    },
    {
        index: 240,
        name: "United States Virgin Islands",
        code: "VI",
        callingCode: "1340",
        currencyCode: "USD",
    },
    {
        index: 241,
        name: "Vietnam",
        code: "VN",
        callingCode: "84",
        currencyCode: "VND",
    },
    {
        index: 242,
        name: "Vanuatu",
        code: "VU",
        callingCode: "678",
        currencyCode: "VUV",
    },
    {
        index: 243,
        name: "Wallis and Futuna",
        code: "WF",
        callingCode: "681",
        currencyCode: "XPF",
    },
    {
        index: 244,
        name: "Samoa",
        code: "WS",
        callingCode: "685",
        currencyCode: "WST",
    },
    {
        index: 245,
        name: "Yemen",
        code: "YE",
        callingCode: "967",
        currencyCode: "YER",
    },
    {
        index: 246,
        name: "South Africa",
        code: "ZA",
        callingCode: "27",
        currencyCode: "ZAR",
    },
    {
        index: 247,
        name: "Zambia",
        code: "ZM",
        callingCode: "260",
        currencyCode: "ZMW",
    },
    {
        index: 248,
        name: "Zimbabwe",
        code: "ZW",
        callingCode: "263",
        currencyCode: "ZWL",
    },
];
