export const countryCode = [
    { country: "Afghanistan", code: "AF", code2: "AFG" },
    { country: "Albania", code: "AL", code2: "ALB" },
    { country: "Algeria", code: "DZ", code2: "DZA" },
    { country: "Andorra", code: "AD", code2: "AND" },
    { country: "Angola", code: "AO", code2: "AGO" },
    { country: "Antigua and Barbuda", code: "AG", code2: "ATG" },
    { country: "Argentina", code: "AR", code2: "ARG" },
    { country: "Armenia", code: "AM", code2: "ARM" },
    { country: "Australia", code: "AU", code2: "AUS" },
    { country: "Austria", code: "AT", code2: "AUT" },
    { country: "Azerbaijan", code: "AZ", code2: "AZE" },
    { country: "Bahamas", code: "BS", code2: "BHS" },
    { country: "Bahrain", code: "BH", code2: "BHR" },
    { country: "Bangladesh", code: "BD", code2: "BGD" },
    { country: "Barbados", code: "BB", code2: "BRB" },
    { country: "Belarus", code: "BY", code2: "BLR" },
    { country: "Belgium", code: "BE", code2: "BEL" },
    { country: "Belize", code: "BZ", code2: "BLZ" },
    { country: "Benin", code: "BJ", code2: "BEN" },
    { country: "Bhutan", code: "BT", code2: "BTN" },
    { country: "Bolivia", code: "BO", code2: "BOL" },
    { country: "Bosnia and Herzegovina", code: "BA", code2: "BIH" },
    { country: "Botswana", code: "BW", code2: "BWA" },
    { country: "Brazil", code: "BR", code2: "BRA" },
    { country: "Brunei", code: "BN", code2: "BRN" },
    { country: "Bulgaria", code: "BG", code2: "BGR" },
    { country: "Burkina Faso", code: "BF", code2: "BFA" },
    { country: "Burundi", code: "BI", code2: "BDI" },
    { country: "Cabo Verde", code: "CV", code2: "CPV" },
    { country: "Cambodia", code: "KH", code2: "KHM" },
    { country: "Cameroon", code: "CM", code2: "CMR" },
    { country: "Canada", code: "CA", code2: "CAN" },
    { country: "Central African Republic", code: "CF", code2: "CAF" },
    { country: "Chad", code: "TD", code2: "TCD" },
    { country: "Chile", code: "CL", code2: "CHL" },
    { country: "China", code: "CN", code2: "CHN" },
    { country: "Colombia", code: "CO", code2: "COL" },
    { country: "Comoros", code: "KM", code2: "COM" },
    {
        country: "Congo, Democratic Republic of the",
        code: "CD",
        code2: "COD",
    },
    { country: "Congo, Republic of the", code: "CG", code2: "COG" },
    { country: "Costa Rica", code: "CR", code2: "CRI" },
    { country: "Croatia", code: "HR", code2: "HRV" },
    { country: "Cuba", code: "CU", code2: "CUB" },
    { country: "Cyprus", code: "CY", code2: "CYP" },
    { country: "Czech Republic", code: "CZ", code2: "CZE" },
    { country: "Denmark", code: "DK", code2: "DNK" },
    { country: "Djibouti", code: "DJ", code2: "DJI" },
    { country: "Dominica", code: "DM", code2: "DMA" },
    { country: "Dominican Republic", code: "DO", code2: "DOM" },
    { country: "East Timor", code: "TL", code2: "TLS" },
    { country: "Ecuador", code: "EC", code2: "ECU" },
    { country: "Egypt", code: "EG", code2: "EGY" },
    { country: "El Salvador", code: "SV", code2: "SLV" },
    { country: "Equatorial Guinea", code: "GQ", code2: "GNQ" },
    { country: "Eritrea", code: "ER", code2: "ERI" },
    { country: "Estonia", code: "EE", code2: "EST" },
    { country: "Eswatini", code: "SZ", code2: "SWZ" },
    { country: "Ethiopia", code: "ET", code2: "ETH" },
    { country: "Fiji", code: "FJ", code2: "FJI" },
    { country: "Finland", code: "FI", code2: "FIN" },
    { country: "France", code: "FR", code2: "FRA" },
    { country: "Gabon", code: "GA", code2: "GAB" },
    { country: "Gambia", code: "GM", code2: "GMB" },
    { country: "Georgia", code: "GE", code2: "GEO" },
    { country: "Germany", code: "DE", code2: "DEU" },
    { country: "Ghana", code: "GH", code2: "GHA" },
    { country: "Greece", code: "GR", code2: "GRC" },
    { country: "Grenada", code: "GD", code2: "GRD" },
    { country: "Guatemala", code: "GT", code2: "GTM" },
    { country: "Guinea", code: "GN", code2: "GIN" },
    { country: "Guinea-Bissau", code: "GW", code2: "GNB" },
    { country: "Guyana", code: "GY", code2: "GUY" },
    { country: "Haiti", code: "HT", code2: "HTI" },
    { country: "Honduras", code: "HN", code2: "HND" },
    { country: "Hungary", code: "HU", code2: "HUN" },
    { country: "Iceland", code: "IS", code2: "ISL" },
    { country: "India", code: "IN", code2: "IND" },
    { country: "Indonesia", code: "ID", code2: "IDN" },
    { country: "Iran", code: "IR", code2: "IRN" },
    { country: "Iraq", code: "IQ", code2: "IRQ" },
    { country: "Ireland", code: "IE", code2: "IRL" },
    { country: "Israel", code: "IL", code2: "ISR" },
    { country: "Italy", code: "IT", code2: "ITA" },
    { country: "Ivory Coast", code: "CI", code2: "CIV" },
    { country: "Jamaica", code: "JM", code2: "JAM" },
    { country: "Japan", code: "JP", code2: "JPN" },
    { country: "Jordan", code: "JO", code2: "JOR" },
    { country: "Kazakhstan", code: "KZ", code2: "KAZ" },
    { country: "Kenya", code: "KE", code2: "KEN" },
    { country: "Kiribati", code: "KI", code2: "KIR" },
    { country: "Korea, North", code: "KP", code2: "PRK" },
    { country: "Korea, South", code: "KR", code2: "KOR" },
    { country: "Kosovo", code: "XK", code2: "XKX" },
    { country: "Kuwait", code: "KW", code2: "KWT" },
    { country: "Kyrgyzstan", code: "KG", code2: "KGZ" },
    { country: "Laos", code: "LA", code2: "LAO" },
    { country: "Latvia", code: "LV", code2: "LVA" },
    { country: "Lebanon", code: "LB", code2: "LBN" },
    { country: "Lesotho", code: "LS", code2: "LSO" },
    { country: "Liberia", code: "LR", code2: "LBR" },
    { country: "Libya", code: "LY", code2: "LBY" },
    { country: "Liechtenstein", code: "LI", code2: "LIE" },
    { country: "Lithuania", code: "LT", code2: "LTU" },
    { country: "Luxembourg", code: "LU", code2: "LUX" },
    { country: "Madagascar", code: "MG", code2: "MDG" },
    { country: "Malawi", code: "MW", code2: "MWI" },
    { country: "Malaysia", code: "MY", code2: "MYS" },
    { country: "Maldives", code: "MV", code2: "MDV" },
    { country: "Mali", code: "ML", code2: "MLI" },
    { country: "Malta", code: "MT", code2: "MLT" },
    { country: "Marshall Islands", code: "MH", code2: "MHL" },
    { country: "Mauritania", code: "MR", code2: "MRT" },
    { country: "Mauritius", code: "MU", code2: "MUS" },
    { country: "Mexico", code: "MX", code2: "MEX" },
    { country: "Micronesia", code: "FM", code2: "FSM" },
    { country: "Moldova", code: "MD", code2: "MDA" },
    { country: "Monaco", code: "MC", code2: "MCO" },
    { country: "Mongolia", code: "MN", code2: "MNG" },
    { country: "Montenegro", code: "ME", code2: "MNE" },
    { country: "Morocco", code: "MA", code2: "MAR" },
    { country: "Mozambique", code: "MZ", code2: "MOZ" },
    { country: "Myanmar", code: "MM", code2: "MMR" },
    { country: "Namibia", code: "NA", code2: "NAM" },
    { country: "Nauru", code: "NR", code2: "NRU" },
    { country: "Nepal", code: "NP", code2: "NPL" },
    { country: "Netherlands", code: "NL", code2: "NLD" },
    { country: "New Zealand", code: "NZ", code2: "NZL" },
    { country: "Nicaragua", code: "NI", code2: "NIC" },
    { country: "Niger", code: "NE", code2: "NER" },
    { country: "Nigeria", code: "NG", code2: "NGA" },
    { country: "North Macedonia", code: "MK", code2: "MKD" },
    { country: "Norway", code: "NO", code2: "NOR" },
    { country: "Oman", code: "OM", code2: "OMN" },
    { country: "Pakistan", code: "PK", code2: "PAK" },
    { country: "Palau", code: "PW", code2: "PLW" },
    { country: "Palestine", code: "PS", code2: "PSE" },
    { country: "Panama", code: "PA", code2: "PAN" },
    { country: "Papua New Guinea", code: "PG", code2: "PNG" },
    { country: "Paraguay", code: "PY", code2: "PRY" },
    { country: "Peru", code: "PE", code2: "PER" },
    { country: "Philippines", code: "PH", code2: "PHL" },
    { country: "Poland", code: "PL", code2: "POL" },
    { country: "Portugal", code: "PT", code2: "PRT" },
    { country: "Qatar", code: "QA", code2: "QAT" },
    { country: "Romania", code: "RO", code2: "ROU" },
    { country: "Russia", code: "RU", code2: "RUS" },
    { country: "Rwanda", code: "RW", code2: "RWA" },
    { country: "Saint Kitts and Nevis", code: "KN", code2: "KNA" },
    { country: "Saint Lucia", code: "LC", code2: "LCA" },
    {
        country: "Saint Vincent and the Grenadines",
        code: "VC",
        code2: "VCT",
    },
    { country: "Samoa", code: "WS", code2: "WSM" },
    { country: "San Marino", code: "SM", code2: "SMR" },
    { country: "Sao Tome and Principe", code: "ST", code2: "STP" },
    { country: "Saudi Arabia", code: "SA", code2: "SAU" },
    { country: "Senegal", code: "SN", code2: "SEN" },
    { country: "Serbia", code: "RS", code2: "SRB" },
    { country: "Seychelles", code: "SC", code2: "SYC" },
    { country: "Sierra Leone", code: "SL", code2: "SLE" },
    { country: "Singapore", code: "SG", code2: "SGP" },
    { country: "Slovakia", code: "SK", code2: "SVK" },
    { country: "Slovenia", code: "SI", code2: "SVN" },
    { country: "Solomon Islands", code: "SB", code2: "SLB" },
    { country: "Somalia", code: "SO", code2: "SOM" },
    { country: "South Africa", code: "ZA", code2: "ZAF" },
    { country: "South Sudan", code: "SS", code2: "SSD" },
    { country: "Spain", code: "ES", code2: "ESP" },
    { country: "Sri Lanka", code: "LK", code2: "LKA" },
    { country: "Sudan", code: "SD", code2: "SDN" },
    { country: "Suriname", code: "SR", code2: "SUR" },
    { country: "Sweden", code: "SE", code2: "SWE" },
    { country: "Switzerland", code: "CH", code2: "CHE" },
    { country: "Syria", code: "SY", code2: "SYR" },
    { country: "Taiwan", code: "TW", code2: "TWN" },
    { country: "Tajikistan", code: "TJ", code2: "TJK" },
    { country: "Tanzania", code: "TZ", code2: "TZA" },
    { country: "Thailand", code: "TH", code2: "THA" },
    { country: "Togo", code: "TG", code2: "TGO" },
    { country: "Tonga", code: "TO", code2: "TON" },
    { country: "Trinidad and Tobago", code: "TT", code2: "TTO" },
    { country: "Tunisia", code: "TN", code2: "TUN" },
    { country: "Turkey", code: "TR", code2: "TUR" },
    { country: "Turkmenistan", code: "TM", code2: "TKM" },
    { country: "Tuvalu", code: "TV", code2: "TUV" },
    { country: "Uganda", code: "UG", code2: "UGA" },
    { country: "Ukraine", code: "UA", code2: "UKR" },
    { country: "United Arab Emirates", code: "AE", code2: "ARE" },
    { country: "United Kingdom", code: "GB", code2: "GBR" },
    { country: "United States", code: "US", code2: "USA" },
    { country: "Uruguay", code: "UY", code2: "URY" },
    { country: "Uzbekistan", code: "UZ", code2: "UZB" },
    { country: "Vanuatu", code: "VU", code2: "VUT" },
    { country: "Vatican City", code: "VA", code2: "VAT" },
    { country: "Venezuela", code: "VE", code2: "VEN" },
    { country: "Vietnam", code: "VN", code2: "VNM" },
    { country: "Yemen", code: "YE", code2: "YEM" },
    { country: "Zambia", code: "ZM", code2: "ZMB" },
    { country: "Zimbabwe", code: "ZW", code2: "ZWE" },
];
