export const currencyOptions = [
    {
        code: "EUR",
        name: "Euro",
        countryCode: "EU",
        countryName: "European Union",
    },
    {
        code: "USD",
        name: "US Dollar",
        countryCode: "US",
        countryName: "United States",
    },
    {
        code: "JPY",
        name: "Japanese Yen",
        countryCode: "JP",
        countryName: "Japan",
    },
    {
        code: "BGN",
        name: "Bulgarian Lev",
        countryCode: "BG",
        countryName: "Bulgaria",
    },
    {
        code: "CZK",
        name: "Czech Republic Koruna",
        countryCode: "CZ",
        countryName: "Czech Republic",
    },
    {
        code: "DKK",
        name: "Danish Krone",
        countryCode: "DK",
        countryName: "Denmark",
    },
    {
        code: "GBP",
        name: "British Pound Sterling",
        countryCode: "GB",
        countryName: "United Kingdom",
    },
    {
        code: "HUF",
        name: "Hungarian Forint",
        countryCode: "HU",
        countryName: "Hungary",
    },
    {
        code: "PLN",
        name: "Polish Zloty",
        countryCode: "PL",
        countryName: "Poland",
    },
    {
        code: "RON",
        name: "Romanian Leu",
        countryCode: "RO",
        countryName: "Romania",
    },
    {
        code: "SEK",
        name: "Swedish Krona",
        countryCode: "SE",
        countryName: "Sweden",
    },
    {
        code: "CHF",
        name: "Swiss Franc",
        countryCode: "CH",
        countryName: "Switzerland",
    },
    {
        code: "ISK",
        name: "Icelandic Króna",
        countryCode: "IS",
        countryName: "Iceland",
    },
    {
        code: "NOK",
        name: "Norwegian Krone",
        countryCode: "NO",
        countryName: "Norway",
    },
    {
        code: "HRK",
        name: "Croatian Kuna",
        countryCode: "HR",
        countryName: "Croatia",
    },
    {
        code: "RUB",
        name: "Russian Ruble",
        countryCode: "RU",
        countryName: "Russia",
    },
    {
        code: "TRY",
        name: "Turkish Lira",
        countryCode: "TR",
        countryName: "Turkey",
    },
    {
        code: "AUD",
        name: "Australian Dollar",
        countryCode: "AU",
        countryName: "Australia",
    },
    {
        code: "BRL",
        name: "Brazilian Real",
        countryCode: "BR",
        countryName: "Brazil",
    },
    {
        code: "CAD",
        name: "Canadian Dollar",
        countryCode: "CA",
        countryName: "Canada",
    },
    {
        code: "CNY",
        name: "Chinese Yuan",
        countryCode: "CN",
        countryName: "China",
    },
    {
        code: "HKD",
        name: "Hong Kong Dollar",
        countryCode: "HK",
        countryName: "Hong Kong",
    },
    {
        code: "IDR",
        name: "Indonesian Rupiah",
        countryCode: "ID",
        countryName: "Indonesia",
    },
    {
        code: "ILS",
        name: "Israeli New Sheqel",
        countryCode: "IL",
        countryName: "Israel",
    },
    {
        code: "INR",
        name: "Indian Rupee",
        countryCode: "IN",
        countryName: "India",
    },
    {
        code: "KRW",
        name: "South Korean Won",
        countryCode: "KR",
        countryName: "South Korea",
    },
    {
        code: "MXN",
        name: "Mexican Peso",
        countryCode: "MX",
        countryName: "Mexico",
    },
    {
        code: "MYR",
        name: "Malaysian Ringgit",
        countryCode: "MY",
        countryName: "Malaysia",
    },
    {
        code: "NZD",
        name: "New Zealand Dollar",
        countryCode: "NZ",
        countryName: "New Zealand",
    },
    {
        code: "PHP",
        name: "Philippine Peso",
        countryCode: "PH",
        countryName: "Philippines",
    },
    {
        code: "SGD",
        name: "Singapore Dollar",
        countryCode: "SG",
        countryName: "Singapore",
    },
    {
        code: "THB",
        name: "Thai Baht",
        countryCode: "TH",
        countryName: "Thailand",
    },
    {
        code: "ZAR",
        name: "South African Rand",
        countryCode: "ZA",
        countryName: "South Africa",
    },
];
