export const procIdOptions = [
    { index: 1, code: "AUB", name: "Asia United Bank CA/SA" },
    { index: 2, code: "BDO", name: "Banco de Oro CA/SA" },
    { index: 3, code: "BPI", name: "BPI CA/SA" },
    { index: 4, code: "BFB", name: "BPI Family Bank" },
    { index: 5, code: "CBC", name: "Chinabank CA/SA" },
    { index: 6, code: "EWB", name: "EastWest CA/SA" },
    { index: 7, code: "LBP", name: "Landbank CA/SA" },
    { index: 8, code: "MBTC", name: "Metrobank CA/SA" },
    { index: 9, code: "PNB", name: "PNB individual CA/SA" },
    {
        index: 10,
        code: "RCBC",
        name: "RCBC CA/SA, RCBC Savings Bank CA/SA, RCBC MyWallet",
    },
    { index: 11, code: "RSB", name: "Robinsons Bank CA/SA" },
    { index: 12, code: "SBC", name: "Security Bank CA/SA" },
    { index: 13, code: "UBP", name: "Unionbank CA/SA, EON" },
    { index: 14, code: "UCPB", name: "UCPB CA/SA" },
    { index: 15, code: "MAY", name: "Maybank" },
    { index: 16, code: "SBA", name: "Sterling Bank of Asia" },
    { index: 17, code: "PBCM", name: "Philippine Bank of Communications" },
    { index: 18, code: "PSB", name: "Philippine Savings Bank" },
    { index: 19, code: "PVB", name: "Philippine Savings Bank" },
    { index: 20, code: "BOC", name: "Bank of Commerce" },
    { index: 21, code: "CBCS", name: "Chinabank Savings Bank" },
    { index: 22, code: "CTBC", name: "Chinatrust" },
    { index: 23, code: "PYMY", name: "Smart PayMaya" },
];

export const procIdFiltered = [
    { index: 1, code: "CEBL", name: "Cebuana Lhuillier Cash Pick-up" },
    { index: 2, code: "LBC", name: "LBC Cash Pick-up" },
    {
        index: 3,
        code: "PLWN",
        name: "Palawan Pawnshop Cash Pick-up (reserved)",
    },
    { index: 4, code: "PRHB", name: "PeraHub Cash Pick-up" },
    { index: 5, code: "RDP", name: "RD Pawnshop Cash Pickup (reserved)" },
    { index: 6, code: "TRMY", name: "TrueMoney Cash Pick-up (reserved)" },
    { index: 7, code: "BITC", name: "Coins.ph Wallet (reserved)" },
    { index: 8, code: "GCSH", name: "Gcash" },
    { index: 9, code: "SMRT", name: "Smart Money (reserved)" },
    {
        index: 10,
        code: "DBP",
        name: "Development Bank of the Philippines (reserved)",
    },
];
